DBSD/Controllers/Members/MembersController.cs
using DBSD.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
/*
*   This is controller that consist all methods used in Member pages.
*
*   Created by Bobir Khaytmatov, Rifat Ahmed and Haoda Zhang for CQUniversity
*/
namespace DBSD.Controllers.Members
{
    public class MembersController : Controller
    {

        public ActionResult Index()
        {
            Validate status = new Validate();
            status = ValidateUser();
            if (status.isAdmin == true)
            {
                return RedirectToAction("Index", "Admin");
            }
            if (status.isUser == true) { 
            HttpCookie myCookie = Request.Cookies["MySuperToken"];
            var manager = new UserServices();
            List<string> data = new List<string>();
            data = manager.CheckToken(myCookie.Value.ToString());
            UserProperties NewUser = new UserProperties();
            if (data.Count != 0) { NewUser.UserName = data[0]; } else { RedirectToAction("Index", "RegisterUser"); }
            return View("Index", NewUser);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult SeeProducts() {
            Validate status = new Validate();
            status = ValidateUser();
            if (status.isAdmin == true)
            {
                return RedirectToAction("Index", "Admin");
            }
            if (status.isUser == true)
            {
                var manager = new ProductDB();
                var items = manager.GetItems();
                return View("SeeProducts", items);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult OrderProduct(Int64 id) {
            HttpCookie myCookie = Request.Cookies["MySuperToken"];
            Validate status = new Validate();
            status = ValidateUser();
            if (status.isUser == true)
            {
                var productManager = new ProductDB();
                var userManager = new UserServices();
                var items = userManager.GetUserIdByToken(myCookie.Value.ToString());
                if (items.Count != 0){
                    UserProperties user = new UserProperties();
                    var data = userManager.CheckToken(myCookie.Value.ToString());
                    productManager.Order(id, items[0]);
                    var orderDetails = productManager.PlaceOrder(items[0]);
                    return View("Success", orderDetails);
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult CompleteOrder() {
            HttpCookie myCookie = Request.Cookies["MySuperToken"];
            Validate status = new Validate();
            status = ValidateUser();
            if (status.isUser == true)
            {
                var manager = new UserServices();
                var id = manager.GetUserIdByToken(myCookie.Value.ToString());
                manager.CompleteOrder(id[0]);
                return View("OrderCompleted");
            }
            return RedirectToAction("Index", "Home");
        }

        public Validate ValidateUser()
        {
            HttpCookie myCookie = Request.Cookies["MySuperToken"];
            Validate response = new Validate();
            if (String.IsNullOrWhiteSpace(myCookie.Value.ToString()))
            {
                response.isAdmin = false;
                response.GreetingName = "";
                return response;
            }
            else
            {
                var manager = new UserServices();
                var data = manager.CheckToken(myCookie.Value.ToString());
                if (data.Count != 0 && data[0] == "bob77")
                {
                    response.GreetingName = data[0];
                    response.isAdmin = true;
                    return response;
                }
                else
                {
                    response.GreetingName = "";
                    response.isUser = true;
                    return response;
                }
            }
        }
    }
}

DBSD/Views/Members/Index.cshtml
@model DBSD.Services.UserProperties
@{
    ViewBag.Title = "Index";
}
<!-- Main page for members of system with See products and Sign out links-->
<div class="heading">
    <p>Hello, user @Model.UserName!</p>
    </div>
     <br />
<hr style="border-color: #e25d29" />
<div class="container">


    @Html.ActionLink("Search for products", "SeeProducts", "Members", new { area = "" }, new { @class = "navbar-brand" })

    @Html.ActionLink("Sign Out", "LogOut", "Home", new { area = "" }, new { @class = "navbar-brand" })
</div>





DBSD/Views/Members/OrderCompleted.cshtml

@{
    ViewBag.Title = "OrderCompleted";
}
<!-- Order completed page-->
<div class="heading">
    <p>Order Completed</p>

    <p>Success!</p>
</div>

DBSD/Views/Members/SeeProducts.cshtml
@model List<DBSD.Services.ProductProperties>
@{
    ViewBag.Title = "SeeProducts";
}
<!-- Products page for members -->
<div class="heading">
    <p>Please choose products Products</p>
    </div>
    @foreach (var i in Model)
    {
        <table>
            <tr>
                <td>@i.ProductName </td>
                <td>@i.ProductDescription </td>
                <td>$@i.ProductPrice </td>
                <td>@Html.ActionLink("Order", "OrderProduct", "Members", new { id = i.ProductId }, new Object())</td>
            </tr>
        </table>
    }

DBSD/Views/Members/Success.cshtml
@model List <DBSD.Services.OrderDetails>
@{
    ViewBag.Title = "Success";
}
<!-- successfull summary of the order -->
<div class="heading">
    <p>Success</p>
    </div>
    Dear customer, your order has been successfully placed, here are the details: <br />
    @foreach (var i in Model)
    {
        <table>
            <tr><td>Order number: </td><td>@i.OrderId </td></tr>
            <tr><td>Order time: </td><td>@i.OrderTime</td></tr>
            <tr><td>Product name: </td><td>@i.PProductName </td></tr>
            <tr><td>Product description: </td><td>@i.PProductDescription</td> </tr>
            <tr><td>Product price: </td><td>@i.PProductPrice</td> </tr>
        </table>
        
        
    }
    @Html.ActionLink("Place order!", "CompleteOrder", "Members")



